[build]
target = "crates/marble-client/index.html"
dist = "dist"
minify = "on_release"

[watch]
watch = ["crates/marble-client", "crates/marble-core"]
ignore = ["target", "crates/marble-server"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"

# Proxy to backend server
[[proxy]]
backend = "http://127.0.0.1:3000/grpc"
rewrite = "/grpc"

[[proxy]]
backend = "http://127.0.0.1:3000/signaling"
rewrite = "/signaling"
